

-- CREATE TABLE product (
--     product_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     product_name text NOT NULL,
--     product_description text NOT NULL,
--     created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
--     updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
-- );

CREATE TABLE voucher_type (
    voucher_type_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_name text NOT NULL,
    nominal numeric NOT NULL,
    duration_month int NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE voucher (
    type_id int NOT NULL REFERENCES voucher_type(voucher_type_id),
    voucher_code text PRIMARY KEY,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    expired_at timestamp with time zone,
    activated_at time without time zone
);

CREATE TABLE partner (
    partner_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_name text NOT NULL,
    address text NOT NULL,
    phone text NOT NULL,
    email text NOT NULL,
    other_contacts text NOT NULL, 
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE invoice (
    invoice_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_id int NOT NULL REFERENCES partner(partner_id),
    payment_method_id text NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE invoice_item (
    invoice_id int NOT NULL REFERENCES invoice(invoice_id),
    invoice_item_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id int NOT NULL REFERENCES voucher_type(voucher_type_id),
    item_amount int NOT NULL,
    item_price int NOT NULL,
    item_discount int NOT NULL
);

CREATE TABLE partner_voucher (
    invoice_id int NOT NULL REFERENCES invoice(invoice_id),
    partner_id int NOT NULL REFERENCES partner(partner_id),
    voucher_code text NOT NULL REFERENCES voucher(voucher_code),
    purchase_value numeric NOT NULL
);


-- CREATE random_string Function

Create or replace function random_string(length integer) returns text as
$$
declare
  chars text[] := '{0,1,2,3,4,5,6,7,8,9,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z}';
  result text := '';
  i integer := 0;
begin
  if length < 0 then
    raise exception 'Given length cannot be less than 0';
  end if;
  for i in 1..length loop
    result := result || chars[1+random()*(array_length(chars, 1)-1)];
  end loop;
  return result;
end;
$$ language plpgsql;


-- SQL STATEMENT
INSERT INTO mind_voucher (product_id, voucher_code, nominal, duration_month, expired_at)
VALUES (1, random_string(8), 100000 , 6, now() + '1 month'::interval * 120)
RETURNING voucher_code;

INSERT INTO mind_partner (name, city)
VALUES
 ('Hendro', 'Ujung Batu');

 INSERT INTO mind_product (name, description)
VALUES
 ('Mindtrex Academy', 'for Brunei');

